### PR TITLE
fix: disallow using numbers for "iat" and "exp"

### LINKED ISSUE #79: "iat" needs to be a number

### PR DESCRIPTION
**Pull request by levino**
fix #79

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -1,16 +1,11 @@
+import { JwtPayload } from 'jsonwebtoken'
 import nock from 'nock'
 import { createJWKS, createKeyPair, signJwt } from './tools'
-export interface JWKSMock {
-  start(): void
-  stop(): void
-  kid(): string
-  token(token: Record<string, unknown>): string
-}
```
Comment (levino) [inline src/index.ts:8]: I think type inference is easier and more robust here.

File: src/tools.ts [hunk 2]
```diff
@@ -144,26 +144,14 @@ export const createKeyPair = () => {
...
 
-export interface JwtPayload {
-  sub?: string
-  iss?: string
-  aud?: string
-  exp?: string
-  nbf?: string
-  iat?: string
-  jti?: string
-}
```
Comment (levino) [inline src/tools.ts:155]: Why do our own? This type comes with `jsonwebtoken`.

File: src/tools.ts [hunk 3]
```diff
@@ -144,26 +144,14 @@ export const createKeyPair = () => {
...
   privateKey: forge.pki.PrivateKey,
   jwtPayload: JwtPayload,
   kid?: string
-) => {
-  const bufferedJwt = Buffer.from(JSON.stringify(jwtPayload))
-  return sign(bufferedJwt, forge.pki.privateKeyToPem(privateKey), {
+) =>
+  sign(jwtPayload, forge.pki.privateKeyToPem(privateKey), {
     header: { kid, alg: 'RS256' },
   })
```
Comment (levino) [inline src/tools.ts:154]: Now this function is much simpler. Maybe this also helps with #64 as a side effect.
